# Generated by Django 5.0.6 on 2024-06-27 12:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('action_type_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('subtype', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Broadcaster',
            fields=[
                ('broadcaster_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='clubs')),
                ('description', models.TextField()),
                ('est_date', models.DateField()),
                ('website', models.URLField(max_length=125)),
                ('social_media', models.URLField(max_length=125)),
                ('email', models.EmailField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, max_length=45, null=True, upload_to='employees')),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('cv', models.FileField(upload_to='CVs')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, max_length=45, null=True, upload_to='players')),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=25)),
                ('height', models.IntegerField()),
                ('social_media', models.CharField(default='NULL', max_length=45, null=True)),
                ('position', models.CharField(max_length=25)),
                ('heath_state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('referee', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='referee_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, max_length=45, null=True, upload_to='referees')),
                ('birth_date', models.DateField()),
                ('cv', models.FileField(upload_to='CVs')),
                ('nationality', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('logo', models.ImageField(upload_to='sponsors')),
                ('website', models.URLField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='stadiums')),
                ('address', models.CharField(max_length=125)),
                ('coordinates', models.CharField(max_length=45)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('casts_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts_broadcaster', to='base.broadcaster')),
            ],
        ),
        migrations.CreateModel(
            name='ClubStad',
            fields=[
                ('club_stad_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_stad_club', to='base.club')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_stad_stadium', to='base.stadium')),
            ],
            options={
                'unique_together': {('club', 'stadium')},
            },
        ),
        migrations.AddField(
            model_name='club',
            name='main_stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_club_stad', to='base.clubstad'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_time', models.DateTimeField()),
                ('host_players', models.CharField(blank=True, max_length=125, null=True)),
                ('away_players', models.CharField(blank=True, max_length=125, null=True)),
                ('weather', models.CharField(default='Stable', max_length=25)),
                ('referee_kit_number', models.SmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('ticket_price', models.IntegerField()),
                ('casts', models.ManyToManyField(through='base.Casts', to='base.broadcaster')),
                ('first_referee_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_first_referee_asist', to='base.referee')),
                ('fourth_official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_fourth_official', to='base.referee')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_referee', to='base.referee')),
                ('second_referee_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_second_referee_asist', to='base.referee')),
            ],
        ),
        migrations.AddField(
            model_name='casts',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casts_match', to='base.match'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject_from_home', models.BooleanField(null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_subject', to=settings.AUTH_USER_MODEL)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_action_type', to='base.actiontype')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_match', to='base.match')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_object', to='base.player')),
            ],
        ),
        migrations.CreateModel(
            name='SampleClub',
            fields=[
                ('sample_club_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='sample_clubs')),
                ('total_points', models.PositiveIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_club_club', to='base.club')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='guest_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest_club', to='base.sampleclub'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_host_club', to='base.sampleclub'),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('kit_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='kits')),
                ('color', models.CharField(max_length=10)),
                ('sample_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_sample_club', to='base.sampleclub')),
            ],
        ),
        migrations.CreateModel(
            name='SamplePlayer',
            fields=[
                ('sample_player_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number_in_team', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('position', models.CharField(max_length=25)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_player_club', to='base.sampleclub')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_player_player', to='base.player')),
            ],
            options={
                'unique_together': {('player', 'club')},
            },
        ),
        migrations.AddField(
            model_name='sampleclub',
            name='players',
            field=models.ManyToManyField(through='base.SamplePlayer', to='base.player'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cup_image', models.ImageField(blank=True, max_length=45, null=True, upload_to='cups')),
                ('date', models.DateField(unique=True)),
                ('clubs', models.ManyToManyField(through='base.SampleClub', to='base.club')),
                ('kit1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_kit1', to='base.kit')),
                ('kit2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_kit2', to='base.kit')),
                ('kit3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_kit3', to='base.kit')),
                ('kit4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_kit4', to='base.kit')),
            ],
        ),
        migrations.AddField(
            model_name='sampleclub',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_club_season', to='base.season'),
        ),
        migrations.CreateModel(
            name='SeaSpon',
            fields=[
                ('sea_spon', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='season_sponsors')),
                ('amount', models.PositiveIntegerField()),
                ('link', models.URLField(max_length=125)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_spon_season', to='base.season')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sea_spon_sponsor', to='base.sponsor')),
            ],
            options={
                'unique_together': {('season', 'sponsor')},
            },
        ),
        migrations.AddField(
            model_name='season',
            name='sponsors',
            field=models.ManyToManyField(through='base.SeaSpon', to='base.sponsor'),
        ),
        migrations.CreateModel(
            name='MatchSpon',
            fields=[
                ('match_spon_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('gif', models.FileField(upload_to='match_sponsors')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_spon_match', to='base.match')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_spon_sponsor', to='base.sponsor')),
            ],
            options={
                'unique_together': {('match', 'sponsor')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='match_spons',
            field=models.ManyToManyField(through='base.MatchSpon', to='base.sponsor'),
        ),
        migrations.CreateModel(
            name='ClubSpon',
            fields=[
                ('club_spon_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_spon_club', to='base.club')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_spon_sponsor', to='base.sponsor')),
            ],
            options={
                'unique_together': {('club', 'sponsor')},
            },
        ),
        migrations.AddField(
            model_name='club',
            name='sponsors',
            field=models.ManyToManyField(through='base.ClubSpon', to='base.sponsor'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stadium', to='base.stadium'),
        ),
        migrations.AddField(
            model_name='club',
            name='stadiums',
            field=models.ManyToManyField(through='base.ClubStad', to='base.stadium'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_match', to='base.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='users',
            field=models.ManyToManyField(through='base.Ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('type_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('s_number', models.IntegerField()),
                ('e_number', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_tag_id', models.CharField(max_length=10)),
                ('matches', models.ManyToManyField(through='base.Ticket', to='base.match')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_stadium', to='base.stadium')),
                ('users', models.ManyToManyField(through='base.Ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_type', to='base.tickettype'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('semester', models.CharField(choices=[('SUMMER', 'summer'), ('WINTER', 'winter')], default='SUMMER', max_length=25)),
                ('duration', models.IntegerField()),
                ('origin_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_origin_club', to='base.sampleclub')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_player', to='base.player')),
                ('target_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_target_club', to='base.sampleclub')),
            ],
            options={
                'unique_together': {('player', 'target_club')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='sample_clubs',
            field=models.ManyToManyField(through='base.Transfer', to='base.sampleclub'),
        ),
        migrations.AlterUniqueTogether(
            name='casts',
            unique_together={('match', 'broadcaster')},
        ),
        migrations.CreateModel(
            name='ClubStaff',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='club_staff_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, max_length=45, null=True, upload_to='club_staff')),
                ('birth_date', models.DateField()),
                ('position', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_staff_club', to='base.sampleclub')),
            ],
            options={
                'unique_together': {('staff', 'club')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sampleclub',
            unique_together={('club', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('host_club', 'guest_club')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'match')},
        ),
    ]
