# Generated by Django 5.0.6 on 2024-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcaster',
            name='e_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broadcaster',
            name='s_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='est_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs'),
        ),
        migrations.AlterField(
            model_name='club',
            name='social_media',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='clubstaff',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], default='Male', max_length=45),
        ),
        migrations.AlterField(
            model_name='kit',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kits'),
        ),
        migrations.AlterField(
            model_name='matchspon',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchspon',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='match_sponsors'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CVs'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='nationality',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sampleclub',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sample_clubs'),
        ),
        migrations.AlterField(
            model_name='sampleclub',
            name='total_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seaspon',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seaspon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='season_sponsors'),
        ),
        migrations.AlterField(
            model_name='seaspon',
            name='link',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='address',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='coordinates',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stadiums'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='e_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='html_tag_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='s_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
