# Generated by Django 5.0.6 on 2024-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_broadcaster_e_date_alter_broadcaster_s_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubstaff',
            name='position',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CVs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
